### PR TITLE
Add RESTore example to "Code To Check Out"

### PR DESCRIPTION
**Pull request by coreh**
Shameless plug? 🙃 As per the suggestion at:

https://twitter.com/swyx/status/985464134144811008

### CODE REVIEW

**Comment by tsiq-swyx** [comment]
cool! hmm why exactly is react suspense even a part of this? this just looks like straight redux data fetching? just trying to understand if its a necessary part of the process?

**Comment by coreh** [comment]
The example I linked to (`examples/react/`) showcases integration with React Suspense, using `<React.unstable_AsyncMode>`, `<React.Timeout>` and throwing promises to suspend rendering. If you feel like the example is only marginally related to React Suspense (since it's more of an integration example for the data store library I'm working on) and therefore more suitable to a different list, that's fine too

**Comment by tsiq-swyx** [comment]
awesome. thank you!

**Comment by coreh** [comment]
🙌

**Pull request merged**
